// app/layout.tsx or app/page.tsx
import type { Metadata } from "next";

export const homeMetadata: Metadata = {
  title: "Blacksof - Soft Trims and NVH Solutions",
  description: "Generated by create next app",
  
  keywords: [
    "soft trims",
    "NVH solutions",
    "automotive",
    "seamless rides",
    "performance",
  ],
  authors: [
    {
      name: "Darshan Boyat",
      url: "https://github.com/darshanboyat",
    },
  ],
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "none",
      "max-snippet": -1,
    },
  },
  openGraph: {
    title: "Blacksof - Soft Trims and NVH Solutions",
    description: "Developed by Darshan Boyat",
    url: "https://blacksof-test-task.vercel.app",
    siteName: "Blacksof",
    locale: "en_US",
    type: "website",
  },
  icons: {
    icon: "/favicon.ico",
  },
};
